<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Overview" data-toc-modified-id="Overview-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Overview</a></span><ul class="toc-item"><li><span><a href="#Motivation" data-toc-modified-id="Motivation-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Motivation</a></span></li><li><span><a href="#Use-cases" data-toc-modified-id="Use-cases-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Use cases</a></span></li><li><span><a href="#Implementation" data-toc-modified-id="Implementation-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Implementation</a></span><ul class="toc-item"><li><span><a href="#Objects,-subsets,-feature-vectors-and-feature-space" data-toc-modified-id="Objects,-subsets,-feature-vectors-and-feature-space-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Objects, subsets, feature vectors and feature space</a></span></li><li><span><a href="#Key-Operations" data-toc-modified-id="Key-Operations-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Key Operations</a></span></li><li><span><a href="#Key-Identities-and-Intuitions-for-Dynamic-Programming" data-toc-modified-id="Key-Identities-and-Intuitions-for-Dynamic-Programming-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Key Identities and Intuitions for Dynamic Programming</a></span></li></ul></li><li><span><a href="#Todo:" data-toc-modified-id="Todo:-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Todo:</a></span></li></ul></li><li><span><a href="#Create-a-set-of-observed-objects-drawn-from-a-binary-feature-space" data-toc-modified-id="Create-a-set-of-observed-objects-drawn-from-a-binary-feature-space-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Create a set of observed objects drawn from a binary feature space</a></span><ul class="toc-item"><li><span><a href="#Define-a-binary-feature-space" data-toc-modified-id="Define-a-binary-feature-space-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Define a binary feature space</a></span></li><li><span><a href="#Create-some-objects" data-toc-modified-id="Create-some-objects-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Create some objects</a></span></li></ul></li><li><span><a href="#Define-the-extensions-of-partial-vectors" data-toc-modified-id="Define-the-extensions-of-partial-vectors-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Define the extensions of partial vectors</a></span><ul class="toc-item"><li><span><a href="#How-do-the-two-methods-for-calculating-extensions-compare?" data-toc-modified-id="How-do-the-two-methods-for-calculating-extensions-compare?-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>How do the two methods for calculating extensions compare?</a></span><ul class="toc-item"><li><span><a href="#Is-the-non-naive-method-correct?" data-toc-modified-id="Is-the-non-naive-method-correct?-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Is the non-naive method correct?</a></span></li></ul></li><li><span><a href="#Is-the-non-naive-method-faster?" data-toc-modified-id="Is-the-non-naive-method-faster?-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Is the non-naive method faster?</a></span></li></ul></li><li><span><a href="#Sketch-inductive-calculation-of-the-extensions-of-increasingly-complex-partial-feature-vectors-in-terms-of-simpler,-already-calculated-ones" data-toc-modified-id="Sketch-inductive-calculation-of-the-extensions-of-increasingly-complex-partial-feature-vectors-in-terms-of-simpler,-already-calculated-ones-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Sketch inductive calculation of the extensions of increasingly complex partial feature vectors in terms of simpler, already calculated ones</a></span><ul class="toc-item"><li><span><a href="#Agreement/conflict" data-toc-modified-id="Agreement/conflict-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Agreement/conflict</a></span></li><li><span><a href="#Union-of-partial-feature-vectors-in-agreement" data-toc-modified-id="Union-of-partial-feature-vectors-in-agreement-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Union of partial feature vectors in agreement</a></span></li><li><span><a href="#Inductive-calculation-of-extensions" data-toc-modified-id="Inductive-calculation-of-extensions-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Inductive calculation of extensions</a></span></li></ul></li><li><span><a href="#Matrix-operations" data-toc-modified-id="Matrix-operations-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Matrix operations</a></span><ul class="toc-item"><li><span><a href="#Representing-$S_i$" data-toc-modified-id="Representing-$S_i$-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Representing $S_i$</a></span><ul class="toc-item"><li><span><a href="#Complexity-calculations" data-toc-modified-id="Complexity-calculations-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Complexity calculations</a></span></li><li><span><a href="#Constructing-$S_i$" data-toc-modified-id="Constructing-$S_i$-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>Constructing $S_i$</a></span></li><li><span><a href="#Constructing-$\overline{S}_i$-given-$S_{i-1}$-or-$\overline{S}_{i-1}$" data-toc-modified-id="Constructing-$\overline{S}_i$-given-$S_{i-1}$-or-$\overline{S}_{i-1}$-5.1.3"><span class="toc-item-num">5.1.3&nbsp;&nbsp;</span>Constructing $\overline{S}_i$ given $S_{i-1}$ or $\overline{S}_{i-1}$</a></span></li></ul></li><li><span><a href="#Decomposing-$S_i$" data-toc-modified-id="Decomposing-$S_i$-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Decomposing $S_i$</a></span></li><li><span><a href="#Calculating-$X_i-=-⟦S_i⟧$:-$S_i-=-B-\cup-V-\iff-⟦S_i⟧-=-⟦B⟧-\cap-⟦V⟧$" data-toc-modified-id="Calculating-$X_i-=-⟦S_i⟧$:-$S_i-=-B-\cup-V-\iff-⟦S_i⟧-=-⟦B⟧-\cap-⟦V⟧$-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Calculating $X_i = ⟦S_i⟧$: $S_i = B \cup V \iff ⟦S_i⟧ = ⟦B⟧ \cap ⟦V⟧$</a></span></li><li><span><a href="#Compressing-arrays-and-matrices" data-toc-modified-id="Compressing-arrays-and-matrices-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Compressing arrays and matrices</a></span><ul class="toc-item"><li><span><a href="#Sparse-representations" data-toc-modified-id="Sparse-representations-5.4.1"><span class="toc-item-num">5.4.1&nbsp;&nbsp;</span>Sparse representations</a></span></li><li><span><a href="#bitarrays" data-toc-modified-id="bitarrays-5.4.2"><span class="toc-item-num">5.4.2&nbsp;&nbsp;</span><code>bitarray</code>s</a></span></li></ul></li></ul></li></ul></div>

In [1]:
import numpy as np

myint = np.int8

In [2]:
from itertools import product, combinations, starmap
from functools import reduce

In [3]:
from tqdm import tqdm

from joblib import Parallel, delayed

J = 15
BACKEND = 'multiprocessing'
# BACKEND = 'loky'
V = 10
PREFER = 'processes'
# PREFER = 'threads'

def par(gen_expr, j=None, backend=None, verbose=None, prefer=None):
    if j is None:
        j = J
    if backend is None:
        backend = BACKEND
    if verbose is None:
        verbose = V
    if prefer is None:
        prefer = PREFER
    return Parallel(n_jobs=j, backend=backend, verbose=verbose, prefer=prefer)(gen_expr)

def identity(x):
    return x

In [4]:
from random import choice

In [5]:
from notebook.services.config import ConfigManager
cm = ConfigManager().update('notebook', {'limit_output': 100000})

In [6]:
# from numba import njit

In [7]:
def np2t(numpy_arrays):
    return tuple(map(tuple, numpy_arrays))

def t2np(tuples):
    return np.array(tuple(map(np.array, tuples)), dtype=myint)

In [8]:
from scipy.special import binom#, comb

# Overview

## Motivation

The goal of this notebook is producing a script that, given a list of observed fully specified feature vectors (i.e. an inventory of observed objects described as feature vectors), can pre-calculate (i.e. write to file) the extension of large numbers of partial feature vectors for subsequent use. 

Examples of such uses include:
 - quickly looking up **all** partial feature vectors with some particular extension.
 - finding the set of **minimal** partial feature vectors with some particular extension.

## Use cases

1. Given a file containing a sequence of fully specified feature vectors, calculate the extension of every logically possible partial feature vector.
2. Given a file containing a sequence of fully specified feature vectors, calculate the extension of every partial feature vector with a non-empty extension.
3. Given a file containing a sequence of fully specified feature vectors and a file containing a set of partially specified feature vectors, calculate the extension of every partial feature vector in the second file.

Currently, only use case 1 is supported.

## Implementation

This is a computationally difficult problem, so on top of 
 - choosing a method of calculation (dynamic programming) to take advantage of substructure and shared computations

the goal is to make as many representations numpy arrays and as many operations vector or matrix operations that can be done via highly optimized linear algebra libraries and taking advantage of any available GPUs.

### Objects, subsets, feature vectors and feature space

 - The number of features is assumed to be fixed and known a priori.
 - A **fully specified feature vector** represents **an object**, or, more precisely, it represents a subset of all possible objects that can contain **at most** one object. In the simplest case, an object is a vector of $-1$s and $+1$s.
 - A **partially specified feature vector** represents **a set of objects**, or more precisely, a subset of the set of all possible objects. In general, a partial feature vector (or "subset vector") is a vector of $0$s, $-1$s, or $+1$s.
 - With respect to a particular set $O$ of $|O| = l$ observed objects (= fully specified feature vectors), the **extension** of a partial feature vector $⟦v⟧^O$ (or just "$⟦v⟧$" when $O$ is clear from context) is given by a vector in $\{0,1\}^l$, where $⟦v⟧_j = 1$ iff $o_j \in ⟦v⟧$ and $⟦v⟧_j = 0$ otherwise.

### Key Operations

The use of $-1$, $0$, and $+1$ facilitates vector operations for calculating 
 - the **intersection of the extensions** of two partial feature vectors.
 - the **combination ('union') of the specifications** of two partial feature vectors.
 - the relationship between these two things.

As explained in more detail below, if two partial feature vectors $u, v$ don't have any conflicting feature values (i.e. $\not \exists j.(u_j = +1 \land v_j = -1) \lor (u_j = -1 \land v_j = +1)$, then 
 - the combination - **union** - of two partial feature vectors can be calculated as `union(u,v) = sign(u + v)` where `+` is vector addition and sign takes a vector and returns a vector indicating the sign (-1, 0, or +1) of its input at each index. Ex: `union(<1, 0, -1>, <1,-1,0>) = <1,-1,-1>`.
 - the **intersection** of two partial feature vectors can be calculated as `intersection(u,v) = sign(equal(u, v) * (u + v))`, where `+`, `*`, `equal`, and `sign` are all element-wise functions on vectors. Ex: `intersection(<1, 0, -1>, <1,-1,0>) = <1,0,0>`.

### Key Identities and Intuitions for Dynamic Programming

Besides being vector-based representations that can be efficiently calculated and parallelized, there is an identity relating the decomposition of partial feature vectors and the decomposition of their extensions that permits an efficient calculation of the extension of more complex feature vectors in terms of the extensions of simpler component  partial feature vectors:
$$⟦u \cup v⟧ = ⟦u⟧ \cap ⟦v⟧$$

It is easy to construct --- or decompose --- any more complex partial feature vector $s$ as the union of a vector $b$ with only one non-zero bit with some (in general) more complex partial vector $v$ (i.e. $v$ has >=1 non-zero bits). Accordingly, the interpretation $⟦s⟧$ of every partial feature vector with $i > 1$ non-zero bits $s \in S_i$ can be calculated by choosing a decomposition $s = b \cup v$ (with $b \in S_1$, $v \in S_{i-1}$) and then calculating $⟦s⟧$ as $⟦b⟧ \cap ⟦v⟧$.

## Todo:

**Basic**
 0. Support naive file IO.
 1. *Space complexity/data structures:* Determine what data structures + operations would be best to support downstream use (e.g. presumably emphasizing speed of access and use over storage space).
 2. *Space complexity:* Write code to support not calculating and/or not storing any partial feature vector with an empty extension. Useful first step might be writing code to count the number of such partial feature vectors.

**Optimization Tarpit**
 0. *Space complexity:* The more features there are, the sparser extension vectors will be - sparse representations should probably be used at least for storage. (I have no idea how efficient operations on sparse representations are, but I imagine they're generally slower than on dense representations unless perhaps you have a very large *and* very sparse matrix.)
 1. *Core representations + processes:* Maybe there are more efficient integer-vector representations and operations (union + intersection) than I chose?
 2. *Core representations + processes:* Maybe manipulating some bit-based representation (see the `bitarray`, `bitstring`, and `BitVector` packages) would be more time efficient?
 3. *Parallelism + space complexity:* Time joblib + do numpy memory mapping of sufficiently small chunks of each $S_i$ at a time.
 4. *Parallelism:* Try pytorch cpu (+ joblib) and gpu representations.
 5. *Parallelism + space complexity:* Use Dask - get it to do more of the work wrt deciding how to store small chunks of very large arrays.
 6. *Parallelism + space complexity:* Use Dask - restructure calculations to take better advantage of laziness in deciding what computations to do.
 
ctrl/cmd+f for "TODO" throughout the notebook...

# Create a set of observed objects drawn from a binary feature space

## Define a binary feature space

In [9]:
num_features = 10

basis_vectors_pos = [np.zeros(num_features, dtype=myint) for each in range(num_features)]
basis_vectors_neg = [np.zeros(num_features, dtype=myint) for each in range(num_features)]
for i,v in enumerate(basis_vectors_pos):
    v[i] = 1
for i,v in enumerate(basis_vectors_neg):
    v[i] = -1
basis_vectors = basis_vectors_pos + basis_vectors_neg

max_num_objects = 2 ** num_features
max_num_objects

max_num_partial_fvs = (2 + 1) ** num_features
max_num_partial_fvs

1024

59049

In [10]:
basis_vectors

[array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8),
 array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0

## Create some objects

In [11]:
def wffv(v):
    allowedValues = {-1,0,1}
    return all([x in allowedValues for x in v])

In [12]:
# actual_num_objects = np.random.randint(max_num_objects)
actual_num_objects = 20
actual_num_objects

assert actual_num_objects < max_num_objects

20

In [13]:
objects = tuple(set([tuple(np.random.randint(2, size=num_features)) for each in range(actual_num_objects)]))
objects = tuple(map(np.array, objects))

def zeroToMinusOne(u):
    return np.array([x if x == 1 else -1 for x in u])
objects = tuple([zeroToMinusOne(o) for o in objects])

actual_num_objects = len(objects)
actual_num_objects
objects

20

(array([-1, -1, -1,  1,  1,  1,  1,  1, -1, -1]),
 array([-1,  1,  1, -1,  1,  1,  1, -1,  1,  1]),
 array([-1,  1, -1,  1, -1,  1,  1,  1,  1, -1]),
 array([-1,  1,  1,  1, -1, -1,  1, -1,  1, -1]),
 array([-1, -1,  1, -1, -1,  1, -1, -1,  1,  1]),
 array([ 1, -1, -1,  1, -1,  1, -1,  1, -1, -1]),
 array([ 1,  1,  1,  1,  1, -1,  1, -1, -1, -1]),
 array([-1,  1,  1,  1,  1, -1,  1, -1, -1, -1]),
 array([-1, -1, -1,  1, -1, -1, -1, -1, -1, -1]),
 array([-1, -1,  1, -1, -1,  1,  1, -1,  1,  1]),
 array([-1,  1,  1,  1, -1,  1,  1,  1, -1, -1]),
 array([-1, -1,  1, -1, -1,  1, -1,  1, -1, -1]),
 array([-1, -1, -1, -1, -1,  1,  1,  1,  1, -1]),
 array([-1, -1,  1, -1, -1,  1,  1, -1, -1, -1]),
 array([-1, -1,  1, -1,  1, -1,  1,  1,  1, -1]),
 array([ 1, -1, -1, -1, -1,  1, -1, -1,  1,  1]),
 array([ 1, -1, -1, -1,  1, -1, -1, -1,  1, -1]),
 array([-1,  1, -1, -1,  1, -1, -1,  1, -1,  1]),
 array([-1, -1,  1,  1, -1,  1,  1, -1,  1, -1]),
 array([-1, -1,  1, -1, -1, -1, -1, -1, -1,  1]))

In [14]:
objectMap = np.array([objects[i] for i in range(len(objects))])
objectMap.shape
objectMap
objectMap[0]

(20, 10)

array([[-1, -1, -1,  1,  1,  1,  1,  1, -1, -1],
       [-1,  1,  1, -1,  1,  1,  1, -1,  1,  1],
       [-1,  1, -1,  1, -1,  1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1, -1,  1, -1,  1, -1],
       [-1, -1,  1, -1, -1,  1, -1, -1,  1,  1],
       [ 1, -1, -1,  1, -1,  1, -1,  1, -1, -1],
       [ 1,  1,  1,  1,  1, -1,  1, -1, -1, -1],
       [-1,  1,  1,  1,  1, -1,  1, -1, -1, -1],
       [-1, -1, -1,  1, -1, -1, -1, -1, -1, -1],
       [-1, -1,  1, -1, -1,  1,  1, -1,  1,  1],
       [-1,  1,  1,  1, -1,  1,  1,  1, -1, -1],
       [-1, -1,  1, -1, -1,  1, -1,  1, -1, -1],
       [-1, -1, -1, -1, -1,  1,  1,  1,  1, -1],
       [-1, -1,  1, -1, -1,  1,  1, -1, -1, -1],
       [-1, -1,  1, -1,  1, -1,  1,  1,  1, -1],
       [ 1, -1, -1, -1, -1,  1, -1, -1,  1,  1],
       [ 1, -1, -1, -1,  1, -1, -1, -1,  1, -1],
       [-1,  1, -1, -1,  1, -1, -1,  1, -1,  1],
       [-1, -1,  1,  1, -1,  1,  1, -1,  1, -1],
       [-1, -1,  1, -1, -1, -1, -1, -1, -1,  1]])

array([-1, -1, -1,  1,  1,  1,  1,  1, -1, -1])

In [15]:
def getIndex(o):
    matches = [i for i,v in enumerate(objectMap) if np.array_equal(v,o)]
    if len(matches) == 0:
        return -1
    assert len(matches) == 1
    return matches[0]

In [16]:
def makeExtensionVector(positive_Indices):
    return np.array([1 if i in positive_Indices else 0 for i in np.arange(objectMap.shape[0])], dtype=myint)

In [17]:
makeExtensionVector([0, 4, 8])

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

# Define the extensions of partial vectors

In [18]:
# @njit
def agree(u,v):
    '''
    Given two vectors u and v, returns a binary vector indicating,
    elementwise, whether u and v 'agree'.
    
    agree(u[i], v[i]) iff (u[i] == 0 or v[i] == 0) or (u[i] == v[i])
    '''
#     return np.array([True if (u[i] == 0 or v[i] == 0) or (u[i] == v[i]) else False 
#                      for i in range(len(u))])
    return np.array([1 if (u[i] == 0 or v[i] == 0) or (u[i] == v[i]) else 0 
                     for i in range(len(u))])

# @njit
def agree_(u,v):
    ag = agree(u,v)
    total_agreement = np.linalg.norm(agree(u,v), 1) == num_features
    return int(total_agreement)
#     if total_agreement:
#         return 1.0
#     return 0.0

In [19]:
# @njit
# def extension_naive_njit(v):
#     matches = np.array([agree_(v,o) for o in objects])
#     return matches

# @njit
def extension_naive(v, asIndexVector=True):
    '''
    The extension of a partial feature vector v is the set of object vectors
    (= fully specified feature vectors) that 'agree' with it.
    '''
    matches = tuple([o for o in objects if agree(v,o).all()])
#     matches = np.array([1.0 if np.linalg.norm(agree(v,o), 1) == num_features else 0.0 for o in objects])
    if asIndexVector:
        return makeExtensionVector([getIndex(o) for o in matches])
    return matches

In [20]:
def make_random_partial_fv():
    return np.random.randint(3, size=num_features) - 1

In [21]:
random_partial_fv = make_random_partial_fv()
while len(extension_naive(random_partial_fv, False)) < 2:
    random_partial_fv = make_random_partial_fv()
random_partial_fv
extension_naive(random_partial_fv, True)

array([ 0, -1,  1, -1,  0,  0,  0,  0,  0,  1])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8)

In [22]:
random_partial_fv
for instance in extension_naive(random_partial_fv, False):
    instance

array([ 0, -1,  1, -1,  0,  0,  0,  0,  0,  1])

array([-1, -1,  1, -1, -1,  1, -1, -1,  1,  1])

array([-1, -1,  1, -1, -1,  1,  1, -1,  1,  1])

array([-1, -1,  1, -1, -1, -1, -1, -1, -1,  1])

In [23]:
# extension_naive(random_partial_fv, True)
# extension_naive_njit(random_partial_fv)

In [24]:
random_instance = choice(list(extension_naive(random_partial_fv, False)))
random_instance

array([-1, -1,  1, -1, -1,  1,  1, -1,  1,  1])

In [25]:
import vg

In [26]:
normalized_0 = vg.normalize

def normalized_1(v):
    return v / np.sqrt(np.sum(v**2))

def normalized_2(v):
    norm=np.linalg.norm(v, ord=2)
    if norm==0:
        norm=np.finfo(v.dtype).eps
    return v/norm

# from https://stackoverflow.com/a/21032099
def normalized_3(a, axis=-1, order=2):
    l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
    l2[l2==0] = 1
    return a / np.expand_dims(l2, axis)

In [27]:
a = np.array([1,0,3])

In [28]:
normalized_0(a)
normalized_1(a)
normalized_2(a)
normalized_3(a)

array([ 0.31622777,  0.        ,  0.9486833 ])

array([ 0.31622777,  0.        ,  0.9486833 ])

array([ 0.31622777,  0.        ,  0.9486833 ])

array([[ 0.31622777,  0.        ,  0.9486833 ]])

In [29]:
normalized = normalized_3
print('s : {0}'.format(  random_partial_fv  ))
print("s': {0}".format( np.abs(random_partial_fv) ))
print('o : {0}'.format( random_instance ))
print("o': {0}".format( np.abs(random_partial_fv) * random_instance ))
np.dot(random_partial_fv, 
       (np.abs(random_partial_fv) * random_instance))
np.dot(random_partial_fv, random_partial_fv)
normalized(random_partial_fv)
normalized(np.abs(random_partial_fv) * random_instance)
np.dot( normalized(random_partial_fv)[0],
        normalized(np.abs(random_partial_fv) * random_instance)[0] )
# np.dot(normalized(random_partial_fv),
#        normalized(np.abs(random_partial_fv) * random_instance))

s : [ 0 -1  1 -1  0  0  0  0  0  1]
s': [0 1 1 1 0 0 0 0 0 1]
o : [-1 -1  1 -1 -1  1  1 -1  1  1]
o': [ 0 -1  1 -1  0  0  0  0  0  1]


4

4

array([[ 0. , -0.5,  0.5, -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5]])

array([[ 0. , -0.5,  0.5, -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5]])

1.0

In [30]:
np.isclose(1.0, 1)

True

In [31]:
normalized = normalized_0

In [32]:
def in_extension(s, o):
    '''
    Given a partial feature vector s and a fully specified object vector o,
    returns True iff o ∈ ⟦s⟧ and False otherwise.
    '''
    if np.array_equal( s, np.zeros(s.shape) ):
        return True
    
    s_ = np.abs(s)
    o_ = s_ * o
    s_normed = normalized(s)#[0] #uncomment the last part here if normalized == normalized_3
    o_normed = normalized(o_)#[0]
    pr = np.dot(s_normed, o_normed)
#     return pr
#     return pr == 1.0 # WRONG
    return np.isclose(1.0, pr)

def extension(s, asIndexVector=True):
    matches = tuple([o for o in objects if in_extension(s, o)])
    if asIndexVector:
        return makeExtensionVector([getIndex(o) for o in matches])
    return matches

extension(random_partial_fv, True)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8)

In [33]:
extension_naive(random_partial_fv)
extension(random_partial_fv)
np.array_equal(extension_naive(random_partial_fv), extension(random_partial_fv))

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8)

True

In [34]:
random_instance

array([-1, -1,  1, -1, -1,  1,  1, -1,  1,  1])

In [35]:
in_extension(random_partial_fv, random_instance)

True

## How do the two methods for calculating extensions compare?

### Is the non-naive method correct?

In [36]:
trials = int(1e6)
generated_partial_fvs = tuple(map(np.array,
                                  set(map(tuple, 
                                          (make_random_partial_fv() for s in range(trials))))))
len(generated_partial_fvs)

59049

In [37]:
# J = 15
# V = 50

In [38]:
# for num_features = 13, ~20m on wittgenstein with a lot of other things going on in the background
# for num_features = 12, ~12m on wittgenstein with a lot of other things going on in the background
# for num_features = 10, ~1.66m on wittgenstein with a lot of other things going on in the background
#  num_features = 10, normalized_0 => ~1.1m on wittgenstein with a lot of other things going on in the background
#  num_features = 10, normalized_1 => ~1.26m on wittgenstein with a lot of other things going on in the background
#  num_features = 10, normalized_2 => ~1.16m on wittgenstein with a lot of other things going on in the background
#  num_features = 10, normalized_3 => ~1.83m on wittgenstein with a lot of other things going on in the background
subset_vectors_with_mismatch = tuple(s for s in tqdm(generated_partial_fvs) 
                                     if not np.array_equal(extension(s), extension_naive(s)))

# subset_vectors_with_mismatch = par((delayed(identity)(s) for s in generated_partial_fvs 
#                                    if not np.array_equal(extension(s), extension_naive(s))), j=15, verbose=90)

100%|██████████| 59049/59049 [01:09<00:00, 852.77it/s]


In [39]:
J = 16
V = 50
# bizarre behavior: num_features = 10 + 16 jobs -> ~1m on wittgenstein with a lot of other things going on in the background
subset_vectors_with_mismatch = par(delayed(identity)(s) for s in generated_partial_fvs 
                                   if not np.array_equal(extension(s), extension_naive(s)))

[Parallel(n_jobs=16)]: Using backend MultiprocessingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   0 out of   0 | elapsed:  1.1min finished


In [40]:
len(generated_partial_fvs)

59049

In [41]:
len(subset_vectors_with_mismatch)

0

In [42]:
subset_vectors_with_mismatch

[]

## Is the non-naive method faster?

In [43]:
trials = int(1e6)
generated_partial_fvs = tuple(map(np.array,
                                  set(map(tuple, 
                                          (make_random_partial_fv() for s in range(trials))))))
len(generated_partial_fvs)

59049

In [44]:
#~11s for num_features = 10 on wittgenstein under heavy load from other users
naive_extensions = [extension_naive(s) for s in generated_partial_fvs]

In [45]:
#~52s for num_features = 10 on wittgenstein under heavy load from other users
extensions = [extension(s) for s in generated_partial_fvs]

In [46]:
V = 50

In [47]:
# bizarre behavior: num_features = 10 + 16 jobs -> ~2.167m on wittgenstein with a lot of other things going on in the background
naive_extensions = par(delayed(extension_naive)(s) for s in generated_partial_fvs)

[Parallel(n_jobs=16)]: Using backend MultiprocessingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Batch computation too fast (0.0042s.) Setting batch_size=94.
[Parallel(n_jobs=16)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   3 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   4 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   6 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   7 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   8 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   9 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  11 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  12 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  13 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]:

In [48]:
# bizarre behavior: num_features = 10 + 16 jobs -> ~2.5m on wittgenstein with a lot of other things going on in the background
extensions = par(delayed(extension)(s) for s in generated_partial_fvs)

[Parallel(n_jobs=16)]: Using backend MultiprocessingBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Batch computation too fast (0.0052s.) Setting batch_size=76.
[Parallel(n_jobs=16)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   3 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   4 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   5 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   6 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   7 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   8 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done   9 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  10 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  11 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  12 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]: Done  13 tasks      | elapsed:    0.0s
[Parallel(n_jobs=16)]:

[Parallel(n_jobs=16)]: Done 26254 tasks      | elapsed:    2.2s
[Parallel(n_jobs=16)]: Done 26620 tasks      | elapsed:    2.3s
[Parallel(n_jobs=16)]: Done 26986 tasks      | elapsed:    2.3s
[Parallel(n_jobs=16)]: Done 27352 tasks      | elapsed:    2.4s
[Parallel(n_jobs=16)]: Done 27718 tasks      | elapsed:    2.4s
[Parallel(n_jobs=16)]: Done 28084 tasks      | elapsed:    2.4s
[Parallel(n_jobs=16)]: Done 28450 tasks      | elapsed:    2.4s
[Parallel(n_jobs=16)]: Done 28816 tasks      | elapsed:    2.4s
[Parallel(n_jobs=16)]: Done 29182 tasks      | elapsed:    2.4s
[Parallel(n_jobs=16)]: Done 29548 tasks      | elapsed:    2.5s
[Parallel(n_jobs=16)]: Done 29914 tasks      | elapsed:    2.5s
[Parallel(n_jobs=16)]: Done 30280 tasks      | elapsed:    2.6s
[Parallel(n_jobs=16)]: Done 30646 tasks      | elapsed:    2.6s
[Parallel(n_jobs=16)]: Done 31012 tasks      | elapsed:    2.6s
[Parallel(n_jobs=16)]: Done 31378 tasks      | elapsed:    2.6s
[Parallel(n_jobs=16)]: Done 31744 tasks 

Apparently not.

# Sketch inductive calculation of the extensions of increasingly complex partial feature vectors in terms of simpler, already calculated ones

In [49]:
# a = make_random_partial_fv()
a = random_partial_fv
a
extension_naive(a)
extension_naive(a, False)

array([ 0, -1,  1, -1,  0,  0,  0,  0,  0,  1])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8)

(array([-1, -1,  1, -1, -1,  1, -1, -1,  1,  1]),
 array([-1, -1,  1, -1, -1,  1,  1, -1,  1,  1]),
 array([-1, -1,  1, -1, -1, -1, -1, -1, -1,  1]))

In [50]:
b = make_random_partial_fv()
while len(extension_naive(b, False)) < 2:
    b = make_random_partial_fv()

b
extension_naive(b)
extension_naive(b, False)

array([ 0,  0,  1, -1, -1,  0,  0,  0,  0, -1])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int8)

(array([-1, -1,  1, -1, -1,  1, -1,  1, -1, -1]),
 array([-1, -1,  1, -1, -1,  1,  1, -1, -1, -1]))

## Agreement/conflict

Let $u, v$ be partial feature vectors. Recall that 
 - $u_i$ and $v_i$ *agree* iff $u_i = v_i \lor u_i = 0 \lor v_i = 0$
 - $u_i$ and $v_i$ *conflict* iff they do not agree
 - $u$ and $v$ *agree* iff $\forall i$ $agree(u_i, v_i)$
 - $u$ and $v$ *conflict* iff they do not agree

In [51]:
a
b

array([ 0, -1,  1, -1,  0,  0,  0,  0,  0,  1])

array([ 0,  0,  1, -1, -1,  0,  0,  0,  0, -1])

In [52]:
agree(a,b)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [53]:
agree_(a,b)

0

## Union of partial feature vectors in agreement

 - A partial feature vector over $F$ binary features can be thought of as a function in $F \rightarrow {-1, 0, 1}$ (where $0$ represents 'unspecified'). 
 - Suppose $u,v$ are vectors that agree.
 - Treating the functions of $u,v$ as *relations*, we can take the union of their relations  $u \cup v$ to get a new partial feature vector that is at least as specified as either $u$ or $u$, and which in general will have every specified value that is in $u$, every specified value that is in $v$, and no other specified values.
 - Crucially, $⟦u \cup v⟧ = ⟦u⟧ \cap ⟦v⟧$.

In [54]:
def twoToOne(x):
    if x != 2 and x != -2:
        return x
    elif x == 2:
        return 1
    else:
        return -1

twoToOne_v = np.vectorize(twoToOne)
    
def union(u,v):
    assert agree_(u,v)
    return np.sign(u + v)
#     return twoToOne_v(u + v)
#     s = u + v
#     return np.trunc( np.sqrt(np.abs(s)) ) * np.sign(s)

In [55]:
def overlapping_extensions(u,v):
    u_x = set(map(tuple, extension_naive(u, False)))
    v_x = set(map(tuple, extension_naive(v, False)))
    return u_x & v_x != set()

In [56]:
c = make_random_partial_fv()
d = make_random_partial_fv()
while (not agree_(c,d)) or len(extension_naive(c, False)) < 2 or len(extension_naive(d, False)) < 2 or not overlapping_extensions(c,d):
    c = make_random_partial_fv()
    d = make_random_partial_fv()
c
d
agree_(c,d)
extension_naive(c)
extension_naive(d)

array([-1,  0,  1,  1, -1,  0,  0, -1,  1, -1])

array([ 0, -1,  1,  0, -1,  1,  0,  0,  0, -1])

1

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int8)

In [57]:
c
d
union(c,d)
# union(c,d).nonzero()
# np.vectorize(twoToOne)(union(c,d))

array([-1,  0,  1,  1, -1,  0,  0, -1,  1, -1])

array([ 0, -1,  1,  0, -1,  1,  0,  0,  0, -1])

array([-1, -1,  1,  1, -1,  1,  0, -1,  1, -1])

We can speedily calculate the intersection of two partial feature vectors $u, v$ as follows:

In [58]:
XYs = tuple(product((-1,0,1), (-1,0,1)))
XYs

def foo(x,y):
    return (x == y) * int((x + y) / 2)

for x,y in XYs:
    ((x,y), foo(x,y))
    
def intersection(u, v):
#     return np.equal(u, v) * (u + v) * 0.5
    return np.sign(  np.equal(u, v) * (u + v) )

((-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 0), (0, 1), (1, -1), (1, 0), (1, 1))

((-1, -1), -1)

((-1, 0), 0)

((-1, 1), 0)

((0, -1), 0)

((0, 0), 0)

((0, 1), 0)

((1, -1), 0)

((1, 0), 0)

((1, 1), 1)

In [59]:
print(c)
print(d)
print(intersection(c,d))

[-1  0  1  1 -1  0  0 -1  1 -1]
[ 0 -1  1  0 -1  1  0  0  0 -1]
[ 0  0  1  0 -1  0  0  0  0 -1]


In [60]:
print("c:\t\t{0}".format(c))
print("d:\t\t{0}".format(d))
print("c ∪ d:\t\t{0}".format(union(c,d)))
print("⟦c⟧:\t\t{0}".format(extension_naive(c)))
print("⟦d⟧:\t\t{0}".format(extension_naive(d)))
print("⟦c ∪ d⟧:\t\t{0}".format(extension_naive(union(c,d))))
print("⟦c⟧ ∩ ⟦d⟧:\t{0}".format(intersection(extension_naive(c), extension_naive(d))))

c:		[-1  0  1  1 -1  0  0 -1  1 -1]
d:		[ 0 -1  1  0 -1  1  0  0  0 -1]
c ∪ d:		[-1 -1  1  1 -1  1  0 -1  1 -1]
⟦c⟧:		[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
⟦d⟧:		[0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0]
⟦c ∪ d⟧:		[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
⟦c⟧ ∩ ⟦d⟧:	[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]


## Inductive calculation of extensions

If 
 - $u, v$ are partial feature vectors whose extensions $⟦u⟧$ and $⟦v⟧$ are known
 - $u, v$ are distinct 
 - $u$ and $v$ are partial feature vectors that agree

then $⟦u \cup v⟧ = ⟦u⟧ \cap ⟦v⟧$.

Accordingly, let $K$ represent the set of partial feature vectors with known extensions at any given point in time.

$K$ can be constructed as $K = K_0 \cup K_1 \cup ... K_i ... \cup K_m$, where $m$ is the number of defined features and $K_i$ represents the set of partial feature vectors with known extensions and with $i$ specified features.

**Naive calculation of the extension of every partial feature vector**

Every $K_i$ for $i > 1$ can be constructed from $K_1$ and $K_{i-1}$ as follows:
 1. lazily construct the Cartesian product $K_1 \times K_{i-1}$
 2. (lazily) filter the product to obtain only the set of pairs $P = {(b, v)}$ where $b$ and $v$
   - are distinct
   - agree

Then $K_i = \{b \cup v | (b,v) \in P\}$.

This calculation method misses two things:
1. It does not take advantage of the fact that, typically, as $i$ increases, most partial feature vectors $v$ have an empty extension -- and therefore so must the union of $v$ with any choice of $u$: needless calculation will be done.
2. It does not take advantage (or avoid the disadvantage) of the fact that for any choice of distinct and agreeing $b, v$, there are usually other distinct and agreeing $b', v'$ such that $b \cup v = b' \cup v'$:  much calculation will be duplicated.

**Reduced calculation of the extension of empty partial feature vectors**

If $S$ is a set of partial feature vectors, let $\overline{S} = \{v | v \in S \land ⟦v⟧ ≠ ∅ \}$.

Every $\overline{K_i}$ for $i > 1$ can be constructed from $\overline{K}_1$ and $\overline{K}_{i-1}$ as follows:
 1. lazily construct $\overline{K}_{i-1} = \{v | v \in K_{i-1} \land ⟦v⟧ ≠ ∅ \}$
 2. lazily construct the Cartesian product $K_1 \times \overline{K}_{i-1}$
 3. (lazily) filter the product to obtain only the set of pairs $P = {(b, v)}$ where $b$ and $v$
   - are distinct
   - agree

Then $\overline{K}_i = \{b \cup v | (b,v) \in P\}$.

**Avoiding duplicate calculation**

To avoid the second problem mentioned above (duplicate calculation), we must intelligently construct a subset of $K_1 \times K_{i-1}$ that avoids including distinct pairs $(b,v)$ and $(b',v')$ such that $b \cup v = b' \cup v'$.

Perhaps the simplest approach to doing this is going in the 'reverse' order of the first approach:
 1. Construct $S_i$, the set of all partial feature vectors with $i$ specified features. ($K_i$ will eventually equal $S_i$.)
 2. For each $s \in S_i$, efficiently choose *any single* decomposition $(b,v)$ of $s$, where $(b,v)$ is a decomposition of $s \in S_i$ iff $b \in S_1 \land v \in S_{i-1} \land b \cup v = s$.
 3. Calculate the extension of each decomposition and add each $s$ to $K_i$.
 
How do we efficiently find such a decomposition of a given $s$?

In [61]:
c
np.nonzero(c) # << key

#adapted from https://stackoverflow.com/a/37323404
def one_hot_stack(indices):
#     n_values = np.max(indices) + 1
    n_values = num_features
    return np.eye(n_values,dtype=myint)[indices] 

def b_factors(partial_feature_vector):
    return one_hot_stack(np.nonzero(partial_feature_vector)) * np.sign(partial_feature_vector)

b_factors(c)
b_0 = b_factors(c)[0]
b_0

c - b_0

array([-1,  0,  1,  1, -1,  0,  0, -1,  1, -1])

(array([0, 2, 3, 4, 7, 8, 9]),)

array([[-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1]])

array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0])

array([ 0,  0,  1,  1, -1,  0,  0, -1,  1, -1])

In [62]:
c
np.nonzero(c)
b_factors(c) * np.sign(c)

array([-1,  0,  1,  1, -1,  0,  0, -1,  1, -1])

(array([0, 2, 3, 4, 7, 8, 9]),)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [63]:
c
d

def decompositions(partial_feature_vector):
    Bs = b_factors(partial_feature_vector)
    Vs = tuple([partial_feature_vector - b for b in Bs])
    together = tuple(zip(Bs, Vs))
    assert all([np.array_equal(partial_feature_vector, t) 
                for t in starmap(union, together)])
    return together

decompositions(c)
decompositions(d)

def decompose(partial_feature_vector):
    Bs = b_factors(partial_feature_vector)
    b = Bs[0]
    v = partial_feature_vector - b
    assert wffv(v)
    assert np.array_equal( union(v, b), partial_feature_vector  )
    return (b, v)

decompose(c)
decompose(d)

array([-1,  0,  1,  1, -1,  0,  0, -1,  1, -1])

array([ 0, -1,  1,  0, -1,  1,  0,  0,  0, -1])

((array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
  array([ 0,  0,  1,  1, -1,  0,  0, -1,  1, -1])),
 (array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([-1,  0,  0,  1, -1,  0,  0, -1,  1, -1])),
 (array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
  array([-1,  0,  1,  0, -1,  0,  0, -1,  1, -1])),
 (array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0]),
  array([-1,  0,  1,  1,  0,  0,  0, -1,  1, -1])),
 (array([ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0]),
  array([-1,  0,  1,  1, -1,  0,  0,  0,  1, -1])),
 (array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
  array([-1,  0,  1,  1, -1,  0,  0, -1,  0, -1])),
 (array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1]),
  array([-1,  0,  1,  1, -1,  0,  0, -1,  1,  0])))

((array([ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0]),
  array([ 0,  0,  1,  0, -1,  1,  0,  0,  0, -1])),
 (array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([ 0, -1,  0,  0, -1,  1,  0,  0,  0, -1])),
 (array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0]),
  array([ 0, -1,  1,  0,  0,  1,  0,  0,  0, -1])),
 (array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
  array([ 0, -1,  1,  0, -1,  0,  0,  0,  0, -1])),
 (array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1]),
  array([ 0, -1,  1,  0, -1,  1,  0,  0,  0,  0])))

(array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([ 0,  0,  1,  1, -1,  0,  0, -1,  1, -1]))

(array([ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([ 0,  0,  1,  0, -1,  1,  0,  0,  0, -1]))

Neither of these two methods, however, take advantage of vector or matrix operations to do this massively in parallel.

# Matrix operations

## Representing $S_i$

The extension operation $⟦⸱⟧$ is a function from partial feature vectors $S$ to some representation of *objects*.

An *object* can be represented as a fully specified feature vector, but directly using this to represent the extension of a partial feature vector $v$ would give us a set of fully specified feature vectors. We want operations to and from matrices.

Accordingly, representing the extension of a partial feature vector $s$ as an *index vector* (i.e. representing an indicator function) gives us a nice, homogeneously shaped representation of the extension of any partial feature vector. 

I.e. if there are $l = |O|$ observed objects, then we can identify $⟦s⟧$ with an $l$-length vector where $⟦s⟧_j$ is 1 iff $o_j \in ⟦s⟧$ and 0 otherwise.

To break things down further, we can specify a distinct interpretation function $⟦⸱⟧_i$ for each number of specified features in the partial feature vectors of interest: $⟦⸱⟧_i : S_i \rightarrow \{0,1\}^l$.

If there are $m$ binary features, then the size of $S_i$ is given by $\binom{m}{i} \cdot 2^i$: 
 - there are $\binom{m}{i}$ ways to choose $i$ distinct indices (features) to specify among $m$ indices (features)
 - for each way of the $\binom{m}{i}$ ways to choose $i$ distinct indices, there are $2^i$ possible assignments (specifications) of feature values
 
Altogether, $\sum\limits_{i=0}^{i=m} \binom{m}{i} \cdot 2^i = 3^m$.

### Complexity calculations

In [64]:
# feature_set_size = num_features
# feature_set_size = 20
feature_set_size = 23 # = num features in bakovic_chart_riggle_hayes{.tsv,.json}

# segment_inventory_size = len(objects)
# segment_inventory_size = 40
segment_inventory_size = 96 # = num symbols in bakovic_chart_riggle_hayes{.tsv,.json}
# segment_inventory_size = 120

bits_per_cell = 2
# bits_per_cell = 4
# bits_per_cell = 8

print('Assuming a feature set of size {0}'.format(feature_set_size))
print('Assuming a segment inventory of size {0}...'.format(segment_inventory_size))
print('Assuming each cell requires ≥ {0} bits of storage'.format(bits_per_cell))

S_cells = []
X_cells = []
for i in range(feature_set_size + 1):
    print('i = {0}'.format(i))

    print('S_{0}:'.format(i))
    print('\t m={0} choose i={1} = {2:,}'.format(segment_inventory_size, i, binom(feature_set_size, i)))
    print('\t 2^i = {0:,}'.format(2 ** i))
    print('\t (m choose i) * 2^i = {0:,}'.format(binom(feature_set_size, i) * (2 ** i)))
    num_pfvs_in_Si = int(binom(feature_set_size, i) * (2 ** i))
    # num_ints_in_Xi = num_pfvs_in_Si * segment_inventory_size
    
    print('\t {0:,} rows = {0:,} partial feature vectors in S_{1}'.format(num_pfvs_in_Si, i))
    cells_per_pfv = int(feature_set_size)
    bits_per_pfv = cells_per_pfv * bits_per_cell
    bits_for_Si = bits_per_pfv * num_pfvs_in_Si
    GB_for_Si = bits_for_Si / 8e9
    print('\t {0} cells/pfv * {1} bits/cell * {2:,} pfvs in S_{3} ⟶ ≥ {4} GB needed for S_{3}'.format(cells_per_pfv, bits_per_cell, num_pfvs_in_Si, i, GB_for_Si))
    cells_for_Si = int(num_pfvs_in_Si * cells_per_pfv)
    S_cells.append(cells_for_Si)

    print('\n')

    print('X_{0}:'.format(i))
    print("\t {0:,} rows=pfvs in S_{1} = {0:,} rows=extensions in X_{1}".format(num_pfvs_in_Si, i))
    print('\t Each extension (as an index vector/naive indicator function) has l = {0} binary cells'.format(segment_inventory_size))
    num_extensions_in_Xi = int(num_pfvs_in_Si)
    cells_per_extension = int(segment_inventory_size)
    bits_per_extension = cells_per_extension * bits_per_cell
    bits_for_Xi = bits_per_extension * num_extensions_in_Xi
    GB_for_Xi = bits_for_Xi / 8e9
    print('\t {0} cells/extension * {1} bits/cell * {2:,} extensions in X_{3} ⟶ ≥ {4} GB needed for X_{3}'.format(cells_per_extension, bits_per_cell, num_extensions_in_Xi, i, GB_for_Xi))
    cells_for_Xi = int(num_extensions_in_Xi * cells_per_extension)
    X_cells.append(cells_for_Xi)
    # print("\t {0:,} rows * {1:,} columns = {2:,} cells in S_{3}".format(num_pfvs_in_Si, segment_inventory_size, num_ints_in_Xi, i))
    
    # num_cells_required = (binom(feature_set_size, i) * (2 ** i)) * segment_inventory_size
    # print("\t minimum of {0:,} GB required if S_{1} stored using {2} bits/int".format(num_cells_required * bits_per_cell / 8e9, i, bits_per_cell))
    # S_cells.append( num_cells_required )
    
    # print('\t 2^{0} = {1:,}'.format(segment_inventory_size, 2 ** segment_inventory_size))
    # print('\t {0:,} rows in S_{1} * {2} objects = {3} cells in X_{1}'.format())
    # num_X_cells_required = 2 ** segment_inventory_size
    # print('\t minimum of {0:,} GB required if X_{1} stored using {2} bits/int'.format(num_X_cells_required * bits_per_cell / 8e9, i, bits_per_cell))
    # X_cells.append( num_X_cells_required )

print('\n')

num_S_cells = sum(S_cells)
num_X_cells = sum(X_cells)
total_number_of_cells = num_S_cells + num_X_cells

print('Total number of S cells = {0:,}'.format(num_S_cells))
print('Total number of X cells = {0:,}'.format(num_X_cells))
print('Total number of cells = {0:,}'.format(total_number_of_cells))

S_bits = num_S_cells * bits_per_cell
X_bits = num_X_cells * bits_per_cell
total_bits = S_bits + X_bits

print('Min. GB for storing S = {0:,}'.format(S_bits / 8e9))
print('Min. GB for storing X = {0:,}'.format(X_bits / 8e9))
print('Min. GB for storing S + X = {0:,}'.format( (S_bits + X_bits) / 8e9 ))

# print('Min. storage required, in GB, assuming each cell requires ≥ {1} bits = {0:,}'.format(n_GB_required, bits_per_cell))

# total_number_of_cells_X = sum(X_cells)
# print('Total number of X_i cells = {0:,}'.format(total_number_of_cells_X))
# n_bits_required_X = total_number_of_cells_X * bits_per_cell
# n_GB_required_X = n_bits_required_X / 8e9
# print('Min. storage required, in GB, assuming each cell requires ≥ {1} bits = {0:,}'.format(n_GB_required_X, bits_per_cell))


Assuming a feature set of size 23
Assuming a segment inventory of size 96...
Assuming each cell requires ≥ 2 bits of storage
i = 0
S_0:
	 m=96 choose i=0 = 1.0
	 2^i = 1
	 (m choose i) * 2^i = 1.0
	 1 rows = 1 partial feature vectors in S_0
	 23 cells/pfv * 2 bits/cell * 1 pfvs in S_0 ⟶ ≥ 5.75e-09 GB needed for S_0


X_0:
	 1 rows=pfvs in S_0 = 1 rows=extensions in X_0
	 Each extension (as an index vector/naive indicator function) has l = 96 binary cells
	 96 cells/extension * 2 bits/cell * 1 extensions in X_0 ⟶ ≥ 2.4e-08 GB needed for X_0
i = 1
S_1:
	 m=96 choose i=1 = 23.0
	 2^i = 2
	 (m choose i) * 2^i = 46.0
	 46 rows = 46 partial feature vectors in S_1
	 23 cells/pfv * 2 bits/cell * 46 pfvs in S_1 ⟶ ≥ 2.645e-07 GB needed for S_1


X_1:
	 46 rows=pfvs in S_1 = 46 rows=extensions in X_1
	 Each extension (as an index vector/naive indicator function) has l = 96 binary cells
	 96 cells/extension * 2 bits/cell * 46 extensions in X_1 ⟶ ≥ 1.104e-06 GB needed for X_1
i = 2
S_2:
	 m=96 choo

In [65]:
feature_set_size = num_features
# feature_set_size = 20
# feature_set_size = 23 # = num features in bakovic_chart_riggle_hayes{.tsv,.json}

segment_inventory_size = len(objects)
# segment_inventory_size = 40
# segment_inventory_size = 96 # = num symbols in bakovic_chart_riggle_hayes{.tsv,.json}
# segment_inventory_size = 120

# bits_per_cell = 2
# bits_per_cell = 4
bits_per_cell = 8

print('Assuming a feature set of size {0}'.format(feature_set_size))
print('Assuming a segment inventory of size {0}...'.format(segment_inventory_size))
print('Assuming each cell requires ≥ {0} bits of storage'.format(bits_per_cell))

S_cells = []
X_cells = []
for i in range(feature_set_size + 1):
    print('i = {0}'.format(i))

    print('S_{0}:'.format(i))
    print('\t m={0} choose i={1} = {2:,}'.format(segment_inventory_size, i, binom(feature_set_size, i)))
    print('\t 2^i = {0:,}'.format(2 ** i))
    print('\t (m choose i) * 2^i = {0:,}'.format(binom(feature_set_size, i) * (2 ** i)))
    num_pfvs_in_Si = int(binom(feature_set_size, i) * (2 ** i))
    # num_ints_in_Xi = num_pfvs_in_Si * segment_inventory_size
    
    print('\t {0:,} rows = {0:,} partial feature vectors in S_{1}'.format(num_pfvs_in_Si, i))
    cells_per_pfv = int(feature_set_size)
    bits_per_pfv = cells_per_pfv * bits_per_cell
    bits_for_Si = bits_per_pfv * num_pfvs_in_Si
    GB_for_Si = bits_for_Si / 8e9
    print('\t {0} cells/pfv * {1} bits/cell * {2:,} pfvs in S_{3} ⟶ ≥ {4} GB needed for S_{3}'.format(cells_per_pfv, bits_per_cell, num_pfvs_in_Si, i, GB_for_Si))
    cells_for_Si = int(num_pfvs_in_Si * cells_per_pfv)
    S_cells.append(cells_for_Si)

    print('\n')

    print('X_{0}:'.format(i))
    print("\t {0:,} rows=pfvs in S_{1} = {0:,} rows=extensions in X_{1}".format(num_pfvs_in_Si, i))
    print('\t Each extension (as an index vector/naive indicator function) has l = {0} binary cells'.format(segment_inventory_size))
    num_extensions_in_Xi = int(num_pfvs_in_Si)
    cells_per_extension = int(segment_inventory_size)
    bits_per_extension = cells_per_extension * bits_per_cell
    bits_for_Xi = bits_per_extension * num_extensions_in_Xi
    GB_for_Xi = bits_for_Xi / 8e9
    print('\t {0} cells/extension * {1} bits/cell * {2:,} extensions in X_{3} ⟶ ≥ {4} GB needed for X_{3}'.format(cells_per_extension, bits_per_cell, num_extensions_in_Xi, i, GB_for_Xi))
    cells_for_Xi = int(num_extensions_in_Xi * cells_per_extension)
    X_cells.append(cells_for_Xi)
    # print("\t {0:,} rows * {1:,} columns = {2:,} cells in S_{3}".format(num_pfvs_in_Si, segment_inventory_size, num_ints_in_Xi, i))
    
    # num_cells_required = (binom(feature_set_size, i) * (2 ** i)) * segment_inventory_size
    # print("\t minimum of {0:,} GB required if S_{1} stored using {2} bits/int".format(num_cells_required * bits_per_cell / 8e9, i, bits_per_cell))
    # S_cells.append( num_cells_required )
    
    # print('\t 2^{0} = {1:,}'.format(segment_inventory_size, 2 ** segment_inventory_size))
    # print('\t {0:,} rows in S_{1} * {2} objects = {3} cells in X_{1}'.format())
    # num_X_cells_required = 2 ** segment_inventory_size
    # print('\t minimum of {0:,} GB required if X_{1} stored using {2} bits/int'.format(num_X_cells_required * bits_per_cell / 8e9, i, bits_per_cell))
    # X_cells.append( num_X_cells_required )

print('\n')

num_S_cells = sum(S_cells)
num_X_cells = sum(X_cells)
total_number_of_cells = num_S_cells + num_X_cells

print('Total number of S cells = {0:,}'.format(num_S_cells))
print('Total number of X cells = {0:,}'.format(num_X_cells))
print('Total number of cells = {0:,}'.format(total_number_of_cells))

S_bits = num_S_cells * bits_per_cell
X_bits = num_X_cells * bits_per_cell
total_bits = S_bits + X_bits

print('Min. GB for storing S = {0:,}'.format(S_bits / 8e9))
print('Min. GB for storing X = {0:,}'.format(X_bits / 8e9))
print('Min. GB for storing S + X = {0:,}'.format( (S_bits + X_bits) / 8e9 ))

# print('Min. storage required, in GB, assuming each cell requires ≥ {1} bits = {0:,}'.format(n_GB_required, bits_per_cell))

# total_number_of_cells_X = sum(X_cells)
# print('Total number of X_i cells = {0:,}'.format(total_number_of_cells_X))
# n_bits_required_X = total_number_of_cells_X * bits_per_cell
# n_GB_required_X = n_bits_required_X / 8e9
# print('Min. storage required, in GB, assuming each cell requires ≥ {1} bits = {0:,}'.format(n_GB_required_X, bits_per_cell))


Assuming a feature set of size 10
Assuming a segment inventory of size 20...
Assuming each cell requires ≥ 8 bits of storage
i = 0
S_0:
	 m=20 choose i=0 = 1.0
	 2^i = 1
	 (m choose i) * 2^i = 1.0
	 1 rows = 1 partial feature vectors in S_0
	 10 cells/pfv * 8 bits/cell * 1 pfvs in S_0 ⟶ ≥ 1e-08 GB needed for S_0


X_0:
	 1 rows=pfvs in S_0 = 1 rows=extensions in X_0
	 Each extension (as an index vector/naive indicator function) has l = 20 binary cells
	 20 cells/extension * 8 bits/cell * 1 extensions in X_0 ⟶ ≥ 2e-08 GB needed for X_0
i = 1
S_1:
	 m=20 choose i=1 = 10.0
	 2^i = 2
	 (m choose i) * 2^i = 20.0
	 20 rows = 20 partial feature vectors in S_1
	 10 cells/pfv * 8 bits/cell * 20 pfvs in S_1 ⟶ ≥ 2e-07 GB needed for S_1


X_1:
	 20 rows=pfvs in S_1 = 20 rows=extensions in X_1
	 Each extension (as an index vector/naive indicator function) has l = 20 binary cells
	 20 cells/extension * 8 bits/cell * 20 extensions in X_1 ⟶ ≥ 4e-07 GB needed for X_1
i = 2
S_2:
	 m=20 choose i=2 = 45.0

In [66]:
for i in range(num_features + 1):
    print('i = {0}'.format(i))
    print('\t m choose i = {0}'.format(binom(num_features, i)))
    print('\t 2^i = {0}'.format(2 ** i))
    print('\t (m choose i) * 2^i = {0}'.format(binom(num_features, i) * (2 ** i)))

i = 0
	 m choose i = 1.0
	 2^i = 1
	 (m choose i) * 2^i = 1.0
i = 1
	 m choose i = 10.0
	 2^i = 2
	 (m choose i) * 2^i = 20.0
i = 2
	 m choose i = 45.0
	 2^i = 4
	 (m choose i) * 2^i = 180.0
i = 3
	 m choose i = 120.0
	 2^i = 8
	 (m choose i) * 2^i = 960.0
i = 4
	 m choose i = 210.0
	 2^i = 16
	 (m choose i) * 2^i = 3360.0
i = 5
	 m choose i = 252.0
	 2^i = 32
	 (m choose i) * 2^i = 8064.0
i = 6
	 m choose i = 210.0
	 2^i = 64
	 (m choose i) * 2^i = 13440.0
i = 7
	 m choose i = 120.0
	 2^i = 128
	 (m choose i) * 2^i = 15360.0
i = 8
	 m choose i = 45.0
	 2^i = 256
	 (m choose i) * 2^i = 11520.0
i = 9
	 m choose i = 10.0
	 2^i = 512
	 (m choose i) * 2^i = 5120.0
i = 10
	 m choose i = 1.0
	 2^i = 1024
	 (m choose i) * 2^i = 1024.0


### Constructing $S_i$

In [67]:
basis_vectors

[array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8),
 array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0], dtype=int8),
 array([ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0

In [68]:
S0 = np.zeros((1,num_features), dtype=myint)
S0
S0.shape

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

(1, 10)

In [69]:
S1 = np.array(basis_vectors, dtype=myint)
S1
S1.shape

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1]], dtype=int8)

(20, 10)

In [70]:
def grand_union(pfvs):
    return reduce(union, pfvs)

In [71]:
def indexChoicesToComponentOptions(index_choices):
    indices = list(index_choices)
    one_hots = one_hot_stack(indices)
    component_options = tuple([(v, -1 * v) for v in one_hots])
    return component_options

def componentOptionsToChoices(component_options):
    choice_combinations = tuple(product(*component_options))
#     return tuple(starmap(union,
#                          choice_combinations))
    return tuple(map(grand_union,
                     choice_combinations))

def make_Si_naive(i):
    index_choices = combinations(range(num_features), i)
    componentOptions = (indexChoicesToComponentOptions(c) for c in index_choices)
    componentChoices = (componentOptionsToChoices(o) for o in componentOptions)
    choices_flattened = reduce(lambda a,b: a + b, componentChoices)
    return np.array(choices_flattened)

In [72]:
S2_naive = make_Si_naive(2)

In [73]:
S2_naive
S2_naive.shape

array([[ 1,  1,  0, ...,  0,  0,  0],
       [ 1, -1,  0, ...,  0,  0,  0],
       [-1,  1,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  1, -1],
       [ 0,  0,  0, ...,  0, -1,  1],
       [ 0,  0,  0, ...,  0, -1, -1]], dtype=int8)

(180, 10)

In [74]:
(2 ** 2) * binom(5,2)

40.0

In [75]:
S3_naive = make_Si_naive(3)

In [76]:
S3_naive.shape
S3_naive

(960, 10)

array([[ 1,  1,  1, ...,  0,  0,  0],
       [ 1,  1, -1, ...,  0,  0,  0],
       [ 1, -1,  1, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ..., -1,  1, -1],
       [ 0,  0,  0, ..., -1, -1,  1],
       [ 0,  0,  0, ..., -1, -1, -1]], dtype=int8)

In [77]:
Ss_naive = [S0, S1]
for i in range(2, num_features+1):
    Ss_naive.append(make_Si_naive(i))

In [78]:
num_features
2 * num_features

for Si in Ss_naive:
    Si.shape

10

20

(1, 10)

(20, 10)

(180, 10)

(960, 10)

(3360, 10)

(8064, 10)

(13440, 10)

(15360, 10)

(11520, 10)

(5120, 10)

(1024, 10)

In [79]:
#TODO/optimization: this could/should be parallelized
def make_Si(i, Sj):
    assert i > 1
    # NB j = i-1
#     print('i = {0}'.format(i))
#     print('\t|S1 x Sj| = {0}'.format(len(tuple(product(S1, Sj)))))
    Si_ = np.array([union(u,v) for u,v in filter(lambda pair: agree_(*pair) and not np.array_equal(pair[0], pair[1]), 
                                                 product(S1, Sj))], 
                   dtype=myint)
#     print('\t|Si_| = {0}'.format(Si_.shape))
    Si__ = set(np2t(Si_)) - set(np2t(Sj))
#     print('\t|Si__| = {0}'.format(len(Si__)))
    Si = np.array(tuple(Si__), dtype=myint)
    return Si

In [80]:
Ss = [S0, S1]
for i in range(2, num_features+1):
    Ss.append(make_Si(i, Ss[i-1]))

In [81]:
num_features
2 * num_features

for Si in Ss:
    Si.shape

10

20

(1, 10)

(20, 10)

(180, 10)

(960, 10)

(3360, 10)

(8064, 10)

(13440, 10)

(15360, 10)

(11520, 10)

(5120, 10)

(1024, 10)

In [82]:
for i in range(num_features+1):
    print('i = {0}'.format(i))
    Si = set(np2t(Ss[i]))
    Si_naive = set(np2t(Ss_naive[i]))
    unique_to_Si = Si - Si_naive
    unique_to_Si_naive = Si_naive - Si
    print(unique_to_Si)
    print(unique_to_Si_naive)
    assert Si == Si_naive
    print('\n')

i = 0
set()
set()


i = 1
set()
set()


i = 2
set()
set()


i = 3
set()
set()


i = 4
set()
set()


i = 5
set()
set()


i = 6
set()
set()


i = 7
set()
set()


i = 8
set()
set()


i = 9
set()
set()


i = 10
set()
set()




### Constructing $\overline{S}_i$ given $S_{i-1}$ or $\overline{S}_{i-1}$

In [83]:
extension_naive(random_partial_fv)
extension_naive(random_partial_fv).shape

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int8)

(20,)

In [84]:
def distinct(u, v):
    return not np.array_equal(u, v)

def empty_extension(u):
    return np.array_equal(extension_naive(u), np.zeros((len(objects),), dtype=myint))

def keep(pair):
    u = pair[0]
    v = pair[1]
    consistent = agree_(*pair)
    different = distinct(u, v)
    non_empty = (not empty_extension(u)) and (not empty_extension(v))
    return consistent and different and non_empty

#TODO/optimization: this could/should be parallelized
def make_Si_bar(i, Sj):
    assert i > 1
    # NB j = i-1
#     print('i = {0}'.format(i))
#     print('\t|S1 x Sj| = {0}'.format(len(tuple(product(S1, Sj)))))
    Si_bar_ = np.array([union(u,v) for u,v in filter(keep, product(S1, Sj))],
                       dtype=myint)
#     print('\t|Si_bar_| = {0}'.format(Si_bar_.shape))
    Si_bar__ = set(np2t(Si_bar_)) - set(np2t(Sj))
#     print('\t|Si_bar__| = {0}'.format(len(Si_bar__)))
    Si_bar = np.array(tuple(Si_bar__), dtype=myint)
    return Si_bar

What are the savings (with respect to the current randomly generated set of objects and number of features)?

In [85]:
S2_bar = make_Si_bar(2, S1)
S2_bar.shape
Ss[2].shape

(180, 10)

(180, 10)

In [86]:
S3_bar = make_Si_bar(3, Ss[2])
S3_bar.shape
Ss[3].shape

(960, 10)

(960, 10)

In [87]:
S4_bar = make_Si_bar(4, Ss[3])
S4_bar.shape
Ss[4].shape

(3358, 10)

(3360, 10)

In [88]:
S5_bar = make_Si_bar(5, Ss[4])
S5_bar.shape
Ss[5].shape

(7854, 10)

(8064, 10)

In [89]:
S6_bar = make_Si_bar(6, Ss[5])
S6_bar.shape
Ss[6].shape

(11755, 10)

(13440, 10)

In [90]:
S7_bar = make_Si_bar(7, Ss[6])
S7_bar.shape
Ss[7].shape

(10686, 10)

(15360, 10)

## Decomposing $S_i$

In [91]:
def b_factors_(partial_feature_vectors):
    big_shape = partial_feature_vectors.shape
    num_vectors = big_shape[0]
    
    a_vector = partial_feature_vectors[0]
    num_specified_features = np.sum(np.abs(a_vector))
    
    my_shape = (num_vectors, num_specified_features)
    my_non_zeros = np.reshape(np.nonzero(partial_feature_vectors)[1], my_shape)
#     print(my_non_zeros.shape)
#     my_non_zeros = np.transpose(my_non_zeros, (0, 2, 1))
#     return my_non_zeros
    my_one_hot_stack = one_hot_stack(  my_non_zeros  )#.transpose((0,2,1))
    return my_one_hot_stack * np.sign(partial_feature_vectors).reshape((num_vectors, 1, num_features))

def decompose_(partial_feature_vectors):
    Bs = b_factors_(partial_feature_vectors)
    bs = Bs[:,0,:]
    vs = partial_feature_vectors - bs
    assert all([wffv(v) for v in vs])
    return bs, vs

In [92]:
b_factors_(S2_naive).shape

(180, 2, 10)

In [93]:
S2_naive[2]
np.sign(S2_naive[2])

array([-1,  1,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8)

array([-1,  1,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8)

In [94]:
b_factors_(S2_naive)[2]
one_hot_stack( b_factors_(S2_naive)[2] )

array([[-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int8)

In [95]:
b_factors_(S2_naive)[:,0,:]

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       [-1,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0,  0, ...,  0, -1,  0],
       [ 0,  0,  0, ...,  0, -1,  0]], dtype=int8)

In [96]:
B2, V2 = decompose_(S2_naive)

In [97]:
B2

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       [-1,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0,  0, ...,  0, -1,  0],
       [ 0,  0,  0, ...,  0, -1,  0]], dtype=int8)

In [98]:
S2_naive[2]
b_factors_(S2_naive)[2]

array([-1,  1,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8)

array([[-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [99]:
V2

array([[ 0,  1,  0, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  0, -1],
       [ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  0, -1]], dtype=int8)

In [100]:
S2_naive

array([[ 1,  1,  0, ...,  0,  0,  0],
       [ 1, -1,  0, ...,  0,  0,  0],
       [-1,  1,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  1, -1],
       [ 0,  0,  0, ...,  0, -1,  1],
       [ 0,  0,  0, ...,  0, -1, -1]], dtype=int8)

In [101]:
np.array_equal(B2 + V2, S2_naive)

True

## Calculating $X_i = ⟦S_i⟧$: $S_i = B \cup V \iff ⟦S_i⟧ = ⟦B⟧ \cap ⟦V⟧$

 - **Dimensions:** If $S_i$ is a matrix of dimensions $(\binom{m}{i} \cdot 2^i, m)$, then $⟦S_i⟧ = X_i$ is a matrix of size $(\binom{m}{i} \cdot 2^i, l)$.

 - **Construction:** Just as $S_i$ can be decomposed into the row-wise (well, element-wise) sum of two matrices $B + V = B \cup V$ s.t. all rows of $B$ come from $S_1$ and all rows of $V$ come from $S_{i-1}$, we can construct $X_i = ⟦S_i⟧$ as the row-wise intersection $⟦B⟧ \cap ⟦V⟧$

In [102]:
S2_naive[:5]
B2[:5]
V2[:5]

array([[ 1,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  1,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

array([[ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [103]:
#TODO/optimization: this could/should be parallelized
def extension_naive_(Vs):#, asIndexVectors=True):
    '''
    The extension of a stack of partial feature vectors Vs is 
    a stack of index vectors indicating the corresponding 
    vectors (= fully specified feature vectors) that 'agree' 
    with each partial feature vector in Vs.
    '''
    matches = tuple([[o for o in objects if agree(v,o).all()] for v in Vs])
##     matches = np.array([[1.0 if np.linalg.norm(agree(v,o), 1) == num_features else 0.0 for o in objects]
#                         for v in Vs])
#     if asIndexVector:
#         return makeExtensionVector([getIndex(o) for o in matches])
#     return matches
    extension_vectors = np.array([makeExtensionVector([getIndex(o) for o in matches_v])
                                  for matches_v in matches])
#     assert np.array_equal(extension_vectors, np.array([extension_naive(v) for v in Vs]))
    return extension_vectors

In [104]:
X2_naive = extension_naive_(S2_naive)
X2_naive.shape
X2_naive[:5]

X2_naive_alt = intersection(extension_naive_(B2), 
                            extension_naive_(V2))
X2_naive_alt[:5]

np.array_equal(X2_naive,
               X2_naive_alt)

(180, 20)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

True

In [105]:
X2_naive.nbytes
X2_naive_alt.nbytes

3600

3600

## Compressing arrays and matrices

### Sparse representations

In [116]:
import sparse

In [139]:
def density(a):
    num_cells = reduce(lambda x,y: x * y, a.shape)
    d = len(np.nonzero(a)[0]) / num_cells
    return d

def sparsity(a):
    return 1 - density(a)

In [140]:
random_partial_fv
sparsity(random_partial_fv)

array([ 0, -1,  1, -1,  0,  0,  0,  0,  0,  1])

0.6

In [141]:
sparsity(X2_naive)

X2_naive.nbytes

X2_naive_sparse = sparse.COO(X2_naive)
X2_naive_sparse.nbytes #????

0.75

3600

15300

In [142]:
sparsity(Ss[7])
Ss[7].nbytes

S7_sparse = sparse.COO(Ss[7])
S7_sparse.nbytes

sparsity(S7_bar)
S7_bar.nbytes

0.30000000000000004

153600

1827840

0.30000000000000004

106860

In [147]:
X5 = extension_naive_(Ss[5])
sparsity(X5)
X5.nbytes

X5_sparse = sparse.COO(X5)
X5_sparse.nbytes

0.96875

161280

85680

In [146]:
X7 = extension_naive_(Ss[7])
sparsity(X7)
X7.nbytes

X7_sparse = sparse.COO(X7)
X7_sparse.nbytes

0.9921875

307200

40800

### `bitarray`s

In [107]:
from bitarray import bitarray

In [108]:
codebook = {-1:bitarray('00'),
            0:bitarray('01'),
            1:bitarray('10')}

In [109]:
r = bitarray()
r.encode(codebook, [-1,0,1])
r

bitarray('000110')

In [110]:
r.decode(codebook)

[-1, 0, 1]

In [111]:
def indexArrayToBA(ia):
    return bitarray(list(ia))

def baToIndexArray(ba):
    return np.array(list(map(int, ba.tolist())), dtype=myint)

def indexMatrixToBAs(im):
    return list(map(indexArrayToBA, im))

def basToIndexMatrix(bas):
    return np.array(list(map(baToIndexArray, bas)), dtype=myint)

In [112]:
def pfvToBA(pfv):
    ba = bitarray()
    ba.encode(codebook, list(pfv))
    return ba

def baToPFV(ba):
    return np.array(ba.decode(codebook), dtype=myint)

def pfvsToBAs(pfvs):
    return list(map(pfvToBA, pfvs))

def basToPFVs(bas):
    return np.array(list(map(baToPFV, bas)), dtype=myint)

In [113]:
random_partial_fv
rpfv_b = pfvToBA(random_partial_fv)
rpfv_b

array([ 0, -1,  1, -1,  0,  0,  0,  0,  0,  1])

bitarray('01001000010101010110')

In [114]:
baToPFV(rpfv_b)

array([ 0, -1,  1, -1,  0,  0,  0,  0,  0,  1], dtype=int8)